FROM node:16.16.0 as base

RUN apt-get update && apt-get install -y \
    build-essential \
    libcairo2-dev \
    libpango1.0-dev \
    libjpeg-dev \
    libgif-dev \
    librsvg2-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

FROM base as build

WORKDIR /app

COPY package*.json ./
RUN npm install
RUN npm install canvas --build-from-source

FROM base as prod

WORKDIR /app

COPY --from=build /app/node_modules ./node_modules
COPY main.js master.js *.tsp ./

ENV ALGORITHM="uy734"

EXPOSE 3000

CMD ["node", "master.js"]
