apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-uy734-master
  labels:
    app: nodejs-uy734-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-uy734-master
  template:
    metadata:
      labels:
        app: nodejs-uy734-master
    spec:
      containers:
      - name: nodejs-uy734-app
        image: minaahmadi/ga-master:uy734
        ports:
        - containerPort: 3000
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-uy734-master-srv
spec:
  selector:
    app: nodejs-uy734-master
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-uy734-worker
  labels:
    app: nodejs-uy734-worker
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nodejs-uy734-worker
  template:
    metadata:
      labels:
        app: nodejs-uy734-worker
    spec:
      containers:
      - name: nodejs-app
        image: minaahmadi/ga-worker:uy734
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
